import rawSets, { CardSet } from './setsData';
import withBasePath from './withBasePath';

/**
 * `setsData.ts` is auto-generated by `npm run create:sets` with root-absolute
 * URLs (`/sets/...`), so it stays agnostic of where the site is deployed. The
 * static export can be served from a subpath, so the deployment base path is
 * applied once here.
 *
 * Import sets from this module — never from `setsData` directly (type-only
 * imports of `CardSet`/`SetCard` are fine either way).
 */
const sets: CardSet[] = rawSets.map(set => ({
  ...set,
  cover: set.cover === null ? null : withBasePath(set.cover),
  cards: set.cards.map(card => ({
    ...card,
    thumb: withBasePath(card.thumb),
    full: withBasePath(card.full),
  })),
}));

export type { CardSet, SetCard } from './setsData';

export default sets;
