// Generated by `./scripts/createSetsData.js`

export interface SetCard {
  id: string;
  number: string;
  name: string;
  thumb: string;
  full: string;
  /** Saved card data, or null when this card was promoted without a .json */
  json: string | null;
}

export interface CardSet {
  id: string;
  displayName: string;
  cover: string | null;
  cards: SetCard[];
}

const sets: CardSet[] = [];

export default sets;
